[book]
title = "MovieBox-TUI Documentation"
authors = ["Samir <mesamirh>"]
language = "en"
src = "docs"

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/Graywizard888/MovieBox-Tui-Mastered"
edit-url-template = "https://github.com/Graywizard888/MovieBox-Tui-Mastered/edit/main/{path}"
site-url = "/MovieBox-Tui-Mastered/"
additional-css = ["docs/custom.css"]

[output.html.fold]
enable = true
level = 1
